CREATE OR REPLACE TABLE `hca-sandbox.hca_metadata_pot.fhir_encounters` (
  encounter_id STRING OPTIONS(description="The \"encounter_id\" field uniquely identifies an encounter within a healthcare system. It is crucial for linking related data across different systems and ensuring accurate patient records. This identifier is typically a string and must be unique within the context of the system. It plays a vital role in interoperability, allowing different systems to reference the same encounter. Proper management of encounter IDs is essential for maintaining data integrity and supporting clinical workflows."),
  lastupdated TIMESTAMP OPTIONS(description="The \"lastupdated\" field indicates the most recent date and time when the encounter record was modified. This timestamp is essential for data synchronization and version control, ensuring that the most current information is available across systems. It helps in auditing changes, tracking updates, and maintaining data consistency. In FHIR, this is typically represented as a timestamp with time zone information, allowing for precise tracking of updates in a globally distributed environment."),
  hl7_message_date_time STRING OPTIONS(description="The \"hl7_message_date_time\" field captures the date and time when the HL7 message related to the encounter was generated. This field is crucial for understanding the timing of data exchange and ensuring that messages are processed in the correct sequence. It is typically represented as a string in a standard date-time format. Accurate recording of this timestamp is vital for interoperability, as it helps in correlating messages with clinical events and maintaining the integrity of the data exchange process."),
  hl7_message_date_time_UTC TIMESTAMP OPTIONS(description="The \"hl7_message_date_time_UTC\" field represents the date and time of the HL7 message in Coordinated Universal Time (UTC). This timestamp is crucial for ensuring consistent time representation across different time zones, facilitating accurate data exchange and processing. It helps in maintaining the sequence of events and supports global interoperability by providing a standardized time reference. Accurate UTC timestamps are essential for auditing, troubleshooting, and ensuring the integrity of healthcare data exchanges."),
  hl7_message_control_id STRING OPTIONS(description="The \"hl7_message_control_id\" field is a unique identifier for an HL7 message, used to track and manage message exchanges. This control ID is crucial for ensuring message integrity, allowing systems to detect duplicates, and confirming message delivery. It is typically a string and must be unique within the context of the message exchange. Proper management of control IDs is essential for reliable communication between systems, supporting error handling, and ensuring accurate data processing in healthcare interoperability."),
  meta_latest_source_date_time STRING OPTIONS(description="The \"meta_latest_source_date_time\" field indicates the most recent date and time when the source data for the encounter was updated. This field is crucial for understanding the currency of the data and ensuring that the most up-to-date information is used in clinical decision-making. It is typically represented as a string in a standard date-time format. Accurate recording of this timestamp is essential for data quality, supporting audit trails, and maintaining the integrity of healthcare information systems."),
  intermediate_snapshot_creation_date_time STRING OPTIONS(description="The \"intermediate_snapshot_creation_date_time\" field captures the date and time when an intermediate snapshot of the encounter data was created. This snapshot is crucial for data versioning, allowing systems to track changes and revert to previous states if necessary. It is typically represented as a string in a standard date-time format. Accurate recording of this timestamp is essential for maintaining data integrity, supporting audit trails, and ensuring reliable data management in healthcare systems."),
  final_fhir_write_date_time STRING OPTIONS(description="The \"final_fhir_write_date_time\" field represents the date and time when the encounter data was last written to the FHIR server. This timestamp is crucial for ensuring that the most current data is available for clinical use and interoperability. It is typically represented as a string in a standard date-time format. Accurate recording of this timestamp is essential for data synchronization, supporting audit trails, and maintaining the integrity of healthcare information systems."),
  final_fhir_commit_date_time TIMESTAMP OPTIONS(description="The \"final_fhir_commit_date_time\" field indicates the date and time when the encounter data was committed to the FHIR server. This timestamp is crucial for ensuring data integrity and consistency, marking the point at which data becomes available for use. It is typically represented as a timestamp with time zone information. Accurate recording of this timestamp is essential for data synchronization, supporting audit trails, and maintaining the integrity of healthcare information systems."),
  encounter_version_id STRING OPTIONS(description="The \"encounter_version_id\" field uniquely identifies a specific version of an encounter record. This version ID is crucial for tracking changes, supporting data versioning, and ensuring that the correct version of the data is used in clinical decision-making. It is typically a string and must be unique within the context of the encounter. Proper management of version IDs is essential for maintaining data integrity, supporting audit trails, and ensuring reliable data management in healthcare systems."),
  version_id_fingerprint INTEGER OPTIONS(description="The \"version_id_fingerprint\" field is a unique identifier used to track the version of the FHIR resource. It ensures data integrity and consistency by allowing systems to detect changes or updates to the resource. This field is crucial for maintaining accurate and up-to-date patient records, supporting version control, and facilitating data synchronization across different systems. It is typically generated using a hashing algorithm to create a unique fingerprint of the resource's content."),
  consent_coid STRING OPTIONS(description="The \"consent_coid\" field represents the unique identifier for a patient's consent document within the FHIR framework. It is essential for managing patient privacy and ensuring that healthcare providers have the necessary permissions to access and share patient information. This field is critical for compliance with legal and regulatory requirements, such as HIPAA, and supports the implementation of consent management workflows in healthcare systems."),
  meta_action_code STRING OPTIONS(description="The \"meta_action_code\" field indicates the type of action performed on the FHIR resource, such as creation, update, or deletion. It is vital for audit trails and tracking changes to patient data over time. This field helps healthcare organizations maintain accurate records, supports data governance, and ensures compliance with regulatory standards by providing a clear history of resource modifications."),
  hl7_v2_source_interface STRING OPTIONS(description="The \"hl7_v2_source_interface\" field identifies the source system or interface from which the HL7 v2 message originated. It is crucial for interoperability and data exchange between different healthcare systems. This field helps ensure that data is accurately mapped and integrated into the FHIR resource, supporting seamless communication and coordination of care across diverse healthcare environments."),
  patient_account_num STRING OPTIONS(description="The \"patient_account_num\" field is a unique identifier assigned to a patient's account within a healthcare organization. It is used for billing, financial tracking, and administrative purposes. This field is essential for linking encounters, services, and charges to the correct patient account, ensuring accurate billing and reimbursement, and facilitating efficient revenue cycle management."),
  patient_primary_id STRING OPTIONS(description="The \"patient_primary_id\" field represents the primary identifier for a patient within the healthcare system. It is crucial for accurately identifying and linking patient records across different systems and encounters. This field supports patient safety, continuity of care, and data integrity by ensuring that healthcare providers have access to the correct patient information at all times."),
  network_mnemonic STRING OPTIONS(description="The \"network_mnemonic\" field is a shorthand identifier for the healthcare network or organization associated with the FHIR resource. It is used to facilitate data exchange and interoperability within and across healthcare networks. This field helps ensure that data is correctly attributed to the appropriate network, supporting coordinated care and efficient resource management."),
  medical_record_num STRING OPTIONS(description="The \"medical_record_num\" field is a unique identifier for a patient's medical record within a healthcare organization. It is essential for accessing and managing patient health information, supporting clinical decision-making, and ensuring continuity of care. This field helps healthcare providers quickly retrieve and update patient records, contributing to efficient and effective patient care."),
  coid STRING OPTIONS(description="The \"coid\" field represents a unique identifier for a clinical object or entity within the FHIR framework. It is used to track and manage specific clinical data elements, supporting data integrity and interoperability. This field is crucial for ensuring that clinical information is accurately linked and integrated across different systems and encounters, facilitating comprehensive patient care and data analysis."),
  facility_mnemonic STRING OPTIONS(description="The \"facility_mnemonic\" field is a shorthand identifier for the healthcare facility associated with the FHIR resource. It is used to facilitate data exchange and interoperability within and across healthcare facilities. This field helps ensure that data is correctly attributed to the appropriate facility, supporting coordinated care, resource management, and operational efficiency."),
  fhir_visit_status STRING OPTIONS(description="The \"fhir_visit_status\" field in a FHIR Encounter resource indicates the current status of the encounter, such as planned, in-progress, or completed. This status is crucial for understanding the stage of the patient's interaction with the healthcare system. It helps in workflow management, resource allocation, and clinical decision-making. Accurate status tracking ensures timely interventions and efficient care delivery."),
  fhir_patient_class_code STRING OPTIONS(description="The \"fhir_patient_class_code\" field represents a coded value that categorizes the patient class, such as inpatient, outpatient, or emergency. This classification is essential for operational and billing purposes, influencing resource allocation, care planning, and reimbursement processes. It helps in understanding the level of care required and the setting in which the patient is being treated."),
  fhir_patient_class_display STRING OPTIONS(description="The \"fhir_patient_class_display\" field provides a human-readable description of the patient class code, such as 'Inpatient' or 'Outpatient'. This display value aids in user interfaces and reports, making it easier for healthcare providers to quickly understand the patient's classification without needing to interpret coded values. It enhances communication and documentation clarity."),
  patient_type STRING OPTIONS(description="The \"patient_type\" field categorizes the patient based on specific criteria, such as new or established patient, or by the type of care they are receiving. This classification is important for clinical workflows, resource planning, and billing. It helps in tailoring care plans and ensuring that appropriate services are provided according to the patient's needs and history."),
  admission_type STRING OPTIONS(description="The \"admission_type\" field specifies the nature of the patient's admission, such as elective, emergency, or urgent. This information is critical for prioritizing care, managing hospital resources, and determining the urgency of medical interventions. It also plays a role in billing and reimbursement, as different admission types may have different financial implications."),
  patient_class_code STRING OPTIONS(description="The \"patient_class_code\" field is a coded representation of the patient's class, similar to \"fhir_patient_class_code\". It categorizes the patient as inpatient, outpatient, etc., and is used for operational, clinical, and financial purposes. This code helps in standardizing patient classification across systems, facilitating interoperability and data exchange."),
  account_status_code STRING OPTIONS(description="The \"account_status_code\" field indicates the current status of the patient's account, such as active, closed, or delinquent. This status is important for financial management, billing, and collections. It helps healthcare organizations track the financial aspects of patient care, ensuring that accounts are managed efficiently and that any issues are addressed promptly."),
  vip_indicator_code STRING OPTIONS(description="The \"vip_indicator_code\" field is used to flag a patient as a VIP (Very Important Person), which may affect the level of service or privacy considerations. This code is important for ensuring that VIP patients receive appropriate attention and that their privacy and security needs are met. It helps in managing special requests and maintaining high standards of care."),
  financial_class_code STRING OPTIONS(description="The \"financial_class_code\" field categorizes the patient's financial responsibility, such as self-pay, insured, or government-funded. This classification is crucial for billing, reimbursement, and financial planning. It helps healthcare providers understand the patient's payment source and manage financial transactions accordingly, ensuring accurate and efficient billing processes."),
  mode_of_arrival_code STRING OPTIONS(description="The \"mode_of_arrival_code\" field indicates how the patient arrived at the healthcare facility, such as by ambulance, walk-in, or referral. This information is important for understanding the context of the encounter, planning resources, and managing patient flow. It can also impact triage decisions and the urgency of care provided, ensuring that patients receive timely and appropriate services."),
  accommodation_code STRING OPTIONS(description="The \"accommodation_code\" field in a FHIR Encounter resource represents the specific type of accommodation provided to the patient during the encounter. This can include various types of hospital rooms or wards. It is crucial for resource allocation, billing, and patient management. The code is typically drawn from a standardized code system to ensure consistency across healthcare systems."),
  accommodation_code_category STRING OPTIONS(description="The \"accommodation_code_category\" field categorizes the type of accommodation provided during an encounter. It provides a higher-level classification than the specific accommodation code, aiding in reporting and analysis. This categorization helps in understanding the general type of care environment, such as inpatient, outpatient, or emergency, and is important for operational and financial management."),
  hospital_service_type_code STRING OPTIONS(description="The \"hospital_service_type_code\" field identifies the specific type of service provided during the encounter, such as surgery, radiology, or cardiology. This code is essential for clinical documentation, billing, and resource management. It ensures that the services rendered are accurately recorded and can be used for quality assurance and performance analysis."),
  hospital_service_type_text STRING OPTIONS(description="The \"hospital_service_type_text\" field provides a human-readable description of the service type provided during the encounter. This text complements the service type code by offering a clear, understandable label for healthcare providers and administrative staff. It aids in communication and documentation, ensuring that the nature of the services provided is easily interpretable."),
  admit_source_code STRING OPTIONS(description="The \"admit_source_code\" field indicates the source from which the patient was admitted to the healthcare facility, such as a referral from a physician, transfer from another hospital, or emergency room admission. This information is vital for understanding patient flow, resource allocation, and care coordination. It also plays a role in reimbursement and reporting."),
  discharge_disposition ARRAY<STRUCT<
    code STRING OPTIONS(description="The \"discharge_disposition\" field describes the patient's status and destination upon discharge from the encounter. It includes a code and display text, indicating whether the patient was discharged to home, transferred to another facility, or deceased. This information is crucial for care continuity, resource planning, and quality reporting."),
    display STRING
  >>,
  patient_id STRING OPTIONS(description="The \"patient_id\" field uniquely identifies the patient involved in the encounter. It is a critical element for linking the encounter to the patient's medical record, ensuring accurate documentation, and facilitating continuity of care. This identifier is essential for patient management, billing, and interoperability across healthcare systems."),
  appointment_id STRING OPTIONS(description="The \"appointment_id\" field links the encounter to a specific appointment, if applicable. This connection is important for tracking patient visits, managing schedules, and ensuring that the encounter aligns with planned care activities. It aids in operational efficiency and helps in analyzing appointment adherence and outcomes."),
  account_id STRING OPTIONS(description="The \"account_id\" field associates the encounter with a specific financial account, facilitating billing and financial management. This identifier is crucial for tracking charges, payments, and insurance claims related to the encounter. It ensures that all financial transactions are accurately linked to the appropriate patient and encounter."),
  deceased_date_time STRING OPTIONS(description="The \"deceased_date_time\" field records the date and time of a patient's death, if applicable, during the encounter. This information is critical for clinical documentation, legal reporting, and family communication. It also impacts care planning and resource allocation, ensuring that the healthcare system responds appropriately to the patient's status."),
  admission_date STRING OPTIONS(description="The \"admission_date\" field in a FHIR Encounter resource represents the date and time when the patient was officially admitted to the healthcare facility. Key Considerations: Data Type: Typically represented as a dateTime data type in FHIR, which includes date and time with time zone. Clinical Significance: Marks the start of the encounter, crucial for determining the duration and for clinical and operational purposes. Billing and Reimbursement: Essential for accurate billing and reimbursement calculations. Clinical Documentation: Used to document the patient's admission time for continuity of care and medical record keeping. Quality Improvement: Can be used to analyze admission patterns and improve patient flow. Relationship to Encounter Period: The \"admission_date\" is closely related to the period element of the Encounter resource, which defines the overall timeframe of the encounter. The period.start should generally align with the admission_date."),
  discharge_date STRING OPTIONS(description="The \"discharge_date\" field in a FHIR Encounter resource represents the date and time when the patient was officially discharged from the encounter. Key Considerations: Data Type: Typically represented as an instant data type in FHIR, which is a date and time with time zone. Clinical Significance: Marks the end of the encounter, crucial for determining the duration and for various clinical and operational purposes. Billing and Reimbursement: Essential for accurate billing and reimbursement calculations. Clinical Documentation: Used to document the patient's discharge time for continuity of care and medical record keeping. Quality Improvement: Can be used to analyze length of stay, identify potential delays, and improve patient flow. Relationship to Encounter Period: The \"discharge_date\" is closely related to the period element of the Encounter resource, which defines the overall timeframe of the encounter. The period.end should generally align with the discharge_date."),
  is_valid_date_ind BOOLEAN OPTIONS(description="The \"is_valid_date_ind\" field indicates whether the dates associated with the encounter are valid and reliable. Key Considerations: Data Type: Boolean, representing true or false. Clinical Significance: Ensures data integrity and accuracy, which is crucial for clinical decision-making, billing, and reporting. Data Quality: Helps identify and flag potential data entry errors or inconsistencies in date fields. Operational Impact: Valid dates are essential for scheduling, resource allocation, and patient flow management. Compliance: Ensures adherence to data standards and regulatory requirements. In Summary: The \"is_valid_date_ind\" field is a critical element for maintaining the integrity and reliability of encounter data, impacting various aspects of healthcare delivery and operations."),
  alt_admission_date_time STRING OPTIONS(description="The \"alt_admission_date_time\" field provides an alternative representation of the admission date and time for the encounter. Key Considerations: Data Type: Typically represented as a dateTime data type in FHIR, which includes date and time with time zone. Clinical Significance: Offers flexibility in capturing admission details, accommodating different time zones or formats. Data Consistency: Ensures alignment with the primary admission_date field, supporting data integrity. Operational Use: Useful in scenarios where multiple systems or formats are involved, ensuring accurate data exchange. In Summary: The \"alt_admission_date_time\" field enhances the flexibility and interoperability of encounter data, supporting accurate and consistent documentation across diverse healthcare systems."),
  hl7_admission_date_time STRING OPTIONS(description="The \"hl7_admission_date_time\" field captures the admission date and time in a format compliant with HL7 standards. Key Considerations: Data Type: Typically represented as a dateTime data type in FHIR, which includes date and time with time zone. HL7 Compliance: Ensures compatibility with HL7 messaging standards, facilitating seamless data exchange between systems. Clinical Significance: Marks the start of the encounter, crucial for determining the duration and for clinical and operational purposes. Data Consistency: Supports alignment with other date fields, ensuring data integrity. In Summary: The \"hl7_admission_date_time\" field is essential for maintaining HL7 compliance and interoperability, supporting accurate and consistent documentation across healthcare systems."),
  alt_discharge_date_time STRING OPTIONS(description="The \"alt_discharge_date_time\" field provides an alternative representation of the discharge date and time for the encounter. Key Considerations: Data Type: Typically represented as a dateTime data type in FHIR, which includes date and time with time zone. Clinical Significance: Offers flexibility in capturing discharge details, accommodating different time zones or formats. Data Consistency: Ensures alignment with the primary discharge_date field, supporting data integrity. Operational Use: Useful in scenarios where multiple systems or formats are involved, ensuring accurate data exchange. In Summary: The \"alt_discharge_date_time\" field enhances the flexibility and interoperability of encounter data, supporting accurate and consistent documentation across diverse healthcare systems."),
  hl7_discharge_date_time STRING OPTIONS(description="The \"hl7_discharge_date_time\" field captures the discharge date and time in a format compliant with HL7 standards. Key Considerations: Data Type: Typically represented as a dateTime data type in FHIR, which includes date and time with time zone. HL7 Compliance: Ensures compatibility with HL7 messaging standards, facilitating seamless data exchange between systems. Clinical Significance: Marks the end of the encounter, crucial for determining the duration and for various clinical and operational purposes. Data Consistency: Supports alignment with other date fields, ensuring data integrity. In Summary: The \"hl7_discharge_date_time\" field is essential for maintaining HL7 compliance and interoperability, supporting accurate and consistent documentation across healthcare systems."),
  reason_for_visit_text STRING OPTIONS(description="The \"reason_for_visit_text\" field captures the patient's reason for the encounter in a textual format. Key Considerations: Data Type: String, allowing for free-text entry. Clinical Significance: Provides context for the encounter, aiding in clinical decision-making and care planning. Patient Communication: Reflects the patient's perspective and concerns, supporting patient-centered care. Documentation: Essential for clinical documentation, ensuring comprehensive medical records. In Summary: The \"reason_for_visit_text\" field is a vital component of the FHIR Encounter resource, capturing the patient's reason for the visit in their own words, supporting clinical care and documentation."),
  mt_reason_for_visit_code STRING OPTIONS(description="The \"mt_reason_for_visit_code\" field captures the reason for the encounter using a standardized code. Key Considerations: Data Type: String, representing a coded value. Clinical Significance: Provides a structured representation of the reason for the visit, supporting clinical decision-making and care planning. Interoperability: Facilitates data exchange and integration across systems by using standardized coding systems. Documentation: Enhances the consistency and accuracy of clinical documentation. In Summary: The \"mt_reason_for_visit_code\" field is a crucial element of the FHIR Encounter resource, capturing the reason for the visit in a standardized format, supporting interoperability and clinical care."),
  patient_location ARRAY<STRUCT<
    location_id STRING OPTIONS(description="The \"location_id\" field uniquely identifies a location associated with the patient during the encounter. Key Considerations: Data Type: String, representing a unique identifier. Clinical Significance: Provides a reference to the specific location, supporting care coordination and resource allocation. Interoperability: Facilitates data exchange and integration across systems by using standardized identifiers. In Summary: The \"location_id\" field is a crucial element of the FHIR Encounter resource, capturing the unique identifier for a location associated with the patient, supporting interoperability and clinical care."),
    mnemonic STRING OPTIONS(description="The \"mnemonic\" field provides a shorthand or code for the location associated with the patient during the encounter. Key Considerations: Data Type: String, representing a mnemonic or code. Clinical Significance: Offers a concise reference to the location, supporting care coordination and resource allocation. Documentation: Enhances the consistency and accuracy of clinical documentation. In Summary: The \"mnemonic\" field is a valuable component of the FHIR Encounter resource, capturing a shorthand or code for the location associated with the patient, supporting clinical care and documentation."),
    physical_type STRING OPTIONS(description="The \"physical_type\" field describes the type of physical location associated with the patient during the encounter. Key Considerations: Data Type: String, representing a description of the physical type. Clinical Significance: Provides context for the location, supporting care coordination and resource allocation. Documentation: Enhances the consistency and accuracy of clinical documentation. In Summary: The \"physical_type\" field is a valuable component of the FHIR Encounter resource, capturing the type of physical location associated with the patient, supporting clinical care and documentation.")
  >>,
  emergency_department STRUCT<
    edm_arrived_date_time STRING OPTIONS(description="The 'edm_arrived_date_time' field indicates the exact date and time when the patient arrived at the emergency department. This timestamp is crucial for tracking the patient's journey and calculating wait times."),
    edm_triaged_date_time STRING OPTIONS(description="The 'edm_triaged_date_time' field records the date and time when the patient was triaged in the emergency department. Triage is a critical process that determines the priority of patients' treatments based on the severity of their condition."),
    edm_departure_date_time STRING OPTIONS(description="The 'edm_departure_date_time' field captures the date and time when the patient departed from the emergency department. This information is essential for understanding the duration of the ED visit and for operational metrics."),
    coid STRING OPTIONS(description="The 'coid' field represents a unique identifier for the encounter or visit in the emergency department. It is used to track and reference the specific encounter across systems."),
    priority_rank STRING OPTIONS(description="The 'priority_rank' field indicates the rank or level of urgency assigned to the patient during triage. It helps in prioritizing care delivery based on the patient's condition."),
    priority_code STRING OPTIONS(description="The 'priority_code' field is a coded representation of the patient's triage priority. It is used for standardized communication of urgency levels within and across healthcare systems."),
    priority_text STRING OPTIONS(description="The 'priority_text' field provides a textual description of the patient's triage priority. This field complements the priority code by offering a human-readable explanation."),
    edm_reason_for_visit_code STRING OPTIONS(description="The 'edm_reason_for_visit_code' field contains a coded value representing the reason for the patient's visit to the emergency department. It aids in categorizing and analyzing visit reasons."),
    edm_reason_for_visit_text STRING OPTIONS(description="The 'edm_reason_for_visit_text' field provides a textual description of the reason for the patient's visit to the emergency department. It offers context and detail beyond the coded value."),
    departure_info STRUCT<
      departure_disposition_code STRING OPTIONS(description="The 'departure_disposition_code' field contains a coded value representing the patient's disposition upon departure from the emergency department. It is used for discharge planning and follow-up care."),
      departure_disposition_text STRING OPTIONS(description="The 'departure_disposition_text' field provides a textual description of the patient's disposition upon departure from the emergency department. It complements the coded disposition value."),
      departure_disposition_display STRING OPTIONS(description="The 'departure_disposition_display' field offers a display-friendly version of the patient's disposition upon departure from the emergency department, suitable for user interfaces."),
      departure_condition_code STRING OPTIONS(description="The 'departure_condition_code' field contains a coded value representing the patient's condition at the time of departure from the emergency department. It is important for continuity of care."),
      departure_condition_text STRING OPTIONS(description="The 'departure_condition_text' field provides a textual description of the patient's condition at the time of departure from the emergency department. It offers additional context to the coded condition."),
      departure_condition_display STRING OPTIONS(description="The 'departure_condition_display' field offers a display-friendly version of the patient's condition at the time of departure from the emergency department, suitable for user interfaces."),
      departure_comments STRING OPTIONS(description="The 'departure_comments' field allows for additional comments or notes regarding the patient's departure from the emergency department. It provides space for free-text documentation.")
    >,
    patient_location STRUCT<
      treatment_room STRUCT<
        room_code STRING OPTIONS(description="The 'room_code' field represents a coded identifier for the treatment room where the patient was located in the emergency department. It is used for tracking and logistics."),
        room_text STRING OPTIONS(description="The 'room_text' field provides a textual description of the treatment room where the patient was located in the emergency department. It complements the room code.")
      >,
      edm_location STRUCT<
        location_code STRING OPTIONS(description="The 'location_code' field represents a coded identifier for the specific location within the emergency department where the patient was situated. It aids in navigation and resource allocation."),
        location_text STRING OPTIONS(description="The 'location_text' field provides a textual description of the specific location within the emergency department where the patient was situated. It complements the location code.")
      >,
      reserved_room STRUCT<
        room_code STRING OPTIONS(description="The 'room_code' field represents a coded identifier for the reserved room for the patient in the emergency department. It is used for planning and resource management."),
        room_text STRING OPTIONS(description="The 'room_text' field provides a textual description of the reserved room for the patient in the emergency department. It complements the room code.")
      >
    >,
    edm_transport STRUCT<
      transport_company_code STRING OPTIONS(description="The 'transport_company_code' field contains a coded value representing the company responsible for transporting the patient to or from the emergency department. It is used for logistics and billing."),
      transport_company_display STRING OPTIONS(description="The 'transport_company_display' field provides a display-friendly version of the transport company responsible for the patient's transportation, suitable for user interfaces."),
      transport_id_code STRING OPTIONS(description="The 'transport_id_code' field contains a coded identifier for the specific transport vehicle or service used for the patient's transportation to or from the emergency department."),
      transport_id_display STRING OPTIONS(description="The 'transport_id_display' field provides a display-friendly version of the transport ID, suitable for user interfaces and easy identification of the transport service."),
      transport_call_date_time STRING OPTIONS(description="The 'transport_call_date_time' field records the date and time when the transport service was called for the patient. It is important for tracking response times and coordination.")
    >
  >,
  registration_query ARRAY<STRUCT<
    mnemonic STRING OPTIONS(description="The 'mnemonic' field represents a shorthand or code used to identify a specific question in the registration process. It facilitates quick reference and data entry."),
    question STRING OPTIONS(description="The 'question' field contains the text of a question asked during the patient's registration process. It is used to gather necessary information for patient care and administration."),
    response STRING OPTIONS(description="The 'response' field captures the patient's answer to a specific registration question. It is essential for documenting patient information and preferences.")
  >>,
  insert_timestamp TIMESTAMP OPTIONS(description="The 'insert_timestamp' field records the exact date and time when the encounter data was inserted into the system. It is crucial for data integrity and audit trails.")
)
OPTIONS(
  description="This BigQuery table stores FHIR data related to healthcare encounters, which are interactions between a patient and healthcare provider(s) for the purpose of providing healthcare services or assessing the health status of a patient. Each record in the table corresponds to an encounter resource, capturing details such as the encounter's unique identifier, status, class, type, subject (patient), participant(s), period (start and end times), reason for the encounter, diagnosis, and location. The table is designed to facilitate interoperability and data exchange in healthcare settings by adhering to the FHIR standard, enabling efficient querying and analysis of encounter data for clinical, operational, and research purposes."
);
