ALTER TABLE `hca-sandbox.hca_metadata_pot.fhir_encounters`
SET OPTIONS (
  description = 'This table stores FHIR Encounter resources, representing healthcare encounters between a patient and a healthcare provider.  Data conforms to the FHIR Encounter resource specification and includes details such as encounter class, type, period, location, participants, and related resources.  See the FHIR specification (https://www.hl7.org/fhir/encounter.html) for more information.'
);

ALTER TABLE `hca-sandbox.hca_metadata_pot.fhir_encounters`
ALTER COLUMN `encounter_id` SET OPTIONS (description = 'Unique identifier for the encounter within the source system. Used for tracking and referencing specific encounters.'),
ALTER COLUMN `lastupdated` SET OPTIONS (description = 'Timestamp indicating the last time the encounter record was modified in the source system. Format: ISO 8601. Used for auditing and data provenance.'),
ALTER COLUMN `hl7_message_date_time` SET OPTIONS (description = 'Date/time the original HL7 message was created. Format: Varies based on source system. Used for message tracking and reconciliation.'),
ALTER COLUMN `hl7_message_date_time_UTC` SET OPTIONS (description = 'Date/time the original HL7 message was created in UTC. Format: ISO 8601. Used for accurate temporal ordering of events.'),
ALTER COLUMN `hl7_message_control_id` SET OPTIONS (description = 'Control ID from the original HL7 message. Used for message tracking and deduplication.'),
ALTER COLUMN `meta_latest_source_date_time` SET OPTIONS (description = 'Timestamp of the latest update from the source system. Format: Varies. Used for data provenance.'),
ALTER COLUMN `intermediate_snapshot_creation_date_time` SET OPTIONS (description = 'Timestamp of any intermediate snapshots during processing. Format: Varies. Used for debugging and tracking data transformations.'),
ALTER COLUMN `final_fhir_write_date_time` SET OPTIONS (description = 'Timestamp when the FHIR resource was initially written. Format: Varies. Used for auditing.'),
ALTER COLUMN `final_fhir_commit_date_time` SET OPTIONS (description = 'Timestamp when the FHIR resource was committed to persistent storage. Format: ISO 8601. Used for auditing and data provenance.'),
ALTER COLUMN `encounter_version_id` SET OPTIONS (description = 'Version identifier for the encounter. Used for tracking changes and managing different versions of the encounter record.'),
ALTER COLUMN `version_id_fingerprint` SET OPTIONS (description = 'Integer representation of the version ID. Used for efficient version comparisons.'),
ALTER COLUMN `consent_coid` SET OPTIONS (description = 'COID related to patient consent. Used for managing patient consent and privacy.'),
ALTER COLUMN `meta_action_code` SET OPTIONS (description = 'Action code indicating the type of operation performed (e.g., create, update, delete). Used for auditing and data provenance.'),
ALTER COLUMN `hl7_v2_source_interface` SET OPTIONS (description = 'Identifier for the HL7 v2 source interface. Used for tracking the origin of the data.'),
ALTER COLUMN `patient_account_num` SET OPTIONS (description = 'Patient''s account number within the healthcare system. Used for billing and administrative purposes.'),
ALTER COLUMN `patient_primary_id` SET OPTIONS (description = 'Patient''s primary identifier within the source system. Used for patient matching and identification.'),
ALTER COLUMN `network_mnemonic` SET OPTIONS (description = 'Mnemonic for the healthcare network. Used for organizational context.'),
ALTER COLUMN `medical_record_num` SET OPTIONS (description = 'Patient''s medical record number. Used for patient identification and record retrieval.'),
ALTER COLUMN `coid` SET OPTIONS (description = 'COID representing the organization or system. Used for organizational context.'),
ALTER COLUMN `facility_mnemonic` SET OPTIONS (description = 'Mnemonic for the healthcare facility. Used for organizational context.'),
ALTER COLUMN `fhir_visit_status` SET OPTIONS (description = 'FHIR Encounter.status.  Indicates the current state of the encounter (e.g., planned, arrived, in-progress, finished).'),
ALTER COLUMN `fhir_patient_class_code` SET OPTIONS (description = 'FHIR Encounter.class code. Categorizes the type of encounter (e.g., inpatient, outpatient, emergency).'),
ALTER COLUMN `fhir_patient_class_display` SET OPTIONS (description = 'FHIR Encounter.class display. Human-readable description of the encounter class.'),
ALTER COLUMN `patient_type` SET OPTIONS (description = 'Type of patient (e.g., inpatient, outpatient). Used for classifying encounters.'),
ALTER COLUMN `admission_type` SET OPTIONS (description = 'Type of admission (e.g., emergency, elective). Used for classifying encounters.'),
ALTER COLUMN `patient_class_code` SET OPTIONS (description = 'Patient class code from the source system. Used for classifying encounters.'),
ALTER COLUMN `account_status_code` SET OPTIONS (description = 'Status of the patient account. Used for billing and administrative purposes.'),
ALTER COLUMN `vip_indicator_code` SET OPTIONS (description = 'Indicates if the patient is a VIP. Used for special handling and prioritization.'),
ALTER COLUMN `financial_class_code` SET OPTIONS (description = 'Patient''s financial class. Used for billing and administrative purposes.'),
ALTER COLUMN `mode_of_arrival_code` SET OPTIONS (description = 'How the patient arrived at the facility (e.g., ambulance, walk-in). Used for clinical context.'),
ALTER COLUMN `accommodation_code` SET OPTIONS (description = 'Patient accommodation code (e.g., private room, shared room). Used for administrative purposes.'),
ALTER COLUMN `accommodation_code_category` SET OPTIONS (description = 'Category of the accommodation code. Used for administrative purposes.'),
ALTER COLUMN `hospital_service_type_code` SET OPTIONS (description = 'Type of hospital service provided during the encounter. Used for clinical context.'),
ALTER COLUMN `hospital_service_type_text` SET OPTIONS (description = 'Human-readable description of the hospital service type. Used for clinical context.'),
ALTER COLUMN `admit_source_code` SET OPTIONS (description = 'Source of the admission (e.g., physician referral, emergency room). Used for clinical context.'),
ALTER COLUMN `discharge_disposition` SET OPTIONS (description = 'Information about the patient''s discharge disposition.  Used for care coordination and tracking patient outcomes.'),
ALTER COLUMN `patient_id` SET OPTIONS (description = 'Unique identifier for the patient.  Should be a FHIR id or conform to another patient matching standard.'),
ALTER COLUMN `appointment_id` SET OPTIONS (description = 'Unique identifier for the appointment associated with the encounter. Used for scheduling and appointment management.'),
ALTER COLUMN `account_id` SET OPTIONS (description = 'Unique identifier for the patient account. Used for billing and administrative purposes.'),
ALTER COLUMN `deceased_date_time` SET OPTIONS (description = 'Date and time of the patient''s death, if applicable. Format: Varies. Used for mortality tracking.'),
ALTER COLUMN `admission_date` SET OPTIONS (description = 'Date of admission. Format: Varies. Used for tracking patient flow.'),
ALTER COLUMN `discharge_date` SET OPTIONS (description = 'Date of discharge. Format: Varies. Used for tracking patient flow.'),
ALTER COLUMN `is_valid_date_ind` SET OPTIONS (description = 'Indicator of whether the date information is valid. Used for data quality control.'),
ALTER COLUMN `alt_admission_date_time` SET OPTIONS (description = 'Alternative admission date/time. Format: Varies. Used for data reconciliation.'),
ALTER COLUMN `hl7_admission_date_time` SET OPTIONS (description = 'Admission date/time from the HL7 message. Format: Varies. Used for data reconciliation.'),
ALTER COLUMN `alt_discharge_date_time` SET OPTIONS (description = 'Alternative discharge date/time. Format: Varies. Used for data reconciliation.'),
ALTER COLUMN `hl7_discharge_date_time` SET OPTIONS (description = 'Discharge date/time from the HL7 message. Format: Varies. Used for data reconciliation.'),
ALTER COLUMN `reason_for_visit_text` SET OPTIONS (description = 'Free-text description of the reason for visit. Used for clinical context.'),
ALTER COLUMN `mt_reason_for_visit_code` SET OPTIONS (description = 'Coded reason for visit. Used for clinical context and analysis.'),
ALTER COLUMN `patient_location` SET OPTIONS (description = 'Information about the patient''s location during the encounter. Used for tracking patient flow and resource allocation.'),
ALTER COLUMN `emergency_department` SET OPTIONS (description = 'Specific information related to emergency department encounters. Used for managing emergency care workflows.'),
ALTER COLUMN `registration_query` SET OPTIONS (description = 'Registration questions and responses collected during patient check-in. Used for patient demographics and administrative purposes.'),
ALTER COLUMN `insert_timestamp` SET OPTIONS (description = 'Timestamp indicating when the record was inserted into the current system. Format: ISO 8601. Used for auditing and data provenance.');
 